language: node_js

node_js:
  - "0.10"

before_install:
  - gem update --system
  - gem install compass
  - npm install -g grunt-cli bower

before_script:
  - grunt bgShell:resetdb
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - grunt
  - sleep 3

addons:
  sauce_connect:
    username: "angelcabo3"
    access_key:
      secure: "vaizOF9erSgg89fvebuLt/EjXzqKMOeBjBXrjXYLdv7ayrtv17daDIz2EnU15hPCeqL2w8jKYpptvZTMnk925rMDQz554pD7F7PYMbF8HV4C/xOiqa4+odd660dy6ho/L85CmdoKjZq7eVp2NgUTa/j5AiZ5kzoltsFmZdDy1g4="

notifications:
  slack:
    secure: S6vA1tXv8LA4JuXnbJ/RkrKXYOeD5JUR/MwCA9rH4/6l/9IFDRKVs2TMJ7GJEwj92ql7+hx/e7xnkqMzghRF3crsk4Wsv1i1wmAYr+jvhdtDRcdeHcA/P1wVbQHoSAWBRDPC6BN4+0ICWmiJ6DLa8a8e7C6bRVQpQMjS77RhWBI=
