language: node_js

node_js:
  - "0.10"

services:
  - mongodb

before_install:
  - sudo apt-get install expect
  - gem update --system
  - gem install compass
  - npm install -g grunt-cli bower
  - "curl https://install.meteor.com | /bin/sh"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  slack:
    secure: S6vA1tXv8LA4JuXnbJ/RkrKXYOeD5JUR/MwCA9rH4/6l/9IFDRKVs2TMJ7GJEwj92ql7+hx/e7xnkqMzghRF3crsk4Wsv1i1wmAYr+jvhdtDRcdeHcA/P1wVbQHoSAWBRDPC6BN4+0ICWmiJ6DLa8a8e7C6bRVQpQMjS77RhWBI=

env:
  global:
    - METEOR_DEPLOY_URL=http://parallels-ci.meteor.com
    - METEOR_EMAIL=angelcabo
    - secure: "pKhVMFwr4+Yku5GyeNa+GITG9B58WMA+uyfejk+ioZakhNQ7fzaeDcL5hV1ZCUSRSgGY+vAiyhusgqCVFf9vgHNZhqqlRHOCw90GLwZlZtLj24vrmIbuc6lAoYlR6ytpeZT/Ao2IxCLajQNLqpn8dWqlRE82E4Fu6D6wWeWWyYc="
    - SAUCE_USERNAME=angelcabo3
    - secure: "JJvO3qCxdRQGnyxuvpm+yyKGNfziMMDWOui5u55icFo8EKjNJZVEy/lII4Kt7en4pwwbGiRZnBsJ5JYupBN/KYHoXCGmsTJsj6sTrjPFbpumP2KKZCafMD+yDm5sxrZOcmryewtoqnbXhR5vAgSlQLpJ1kGgp4B5sNlrmdNt/Xs="

script:
  - "expect deploy.exp"
  - "sleep 5"
  - grunt e2e-tests:ci
